language: php

php:
  - '7.1'

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE buildsize_test;'

before_script:
  - cp .env.test .env
  - composer install
  - php artisan key:generate

script:
  - vendov/bin/phpunit
